### PR TITLE
Updating guns

### PR DESCRIPTION
**Pull request by thamid-gamer**
I honestly don't know how to use git

### CODE REVIEW

**Comment by quangaming2929** [comment]
Hi, I just had a glance at your pull request. It was great, but I just have a small question: 
At your LinearBeam constructor 
```java
public LinearBeam(World world, Vector eyeLocation, Vector directionVector, Block targetBlock, int maxHitEntities)
{
  // ...
}
```
This implementation is great but to get the target block you will need a additional collision check

**Comment by thamid-gamer** [comment]
> Hi, I just had a glance at your pull request. It was great, but I just have a small question:
> At your `LinearBeam `constructor
> 
> ```java
> public LinearBeam(World world, Vector eyeLocation, Vector directionVector, Block targetBlock, int maxHitEntities)
> {
>   // ...
> }
> ```
> 
> This implementation is great but to get the target block you will need a additional collision check
> 
> Also I suggest `LinearGun` to abstract class because it prevent user (let say zombie plugin will be the framework for another plugin/project) from instantiate it, because in theory, `LinearGun` is just the class that implement how linear gun work

What do you mean additional collision check? Use the block `BoundingBox`? Might be better than what I did I didn't know blocks had a `BoundingBox` before

I'm not really sure what is gained by making `LinearGun` abstract. None of the methods need to be abstract I believe...?
However, what I was planning to do is allow the potion effects of things like blowdart or flamethrower to be applied. I suppose you could create a method like that and make it abstract.



No idea how to use github still though

**Comment by quangaming2929** [comment]
> What do you mean additional collision check? Use the block BoundingBox? Might be better than what I did I didn't know blocks had a BoundingBox before
Block as a binding box but when the player right click, we don't really know where the target block

After rethinking about it, adding abstract class is not necessary

**Comment by thamid-gamer** [comment]
closing to change some things

**Pull request closed without merging**
